apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: R project template
  description: An r project template built for Backstage.
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
